---
title: "Acoustic Analysis"
author: "Tabea Thies"
date: "`r Sys.Date()`"
output: html_document
---

# Analysis of pure electrode effect of acoustic vowel duration in speakers with PD

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load necessary packages

```{r load_tidyverse, warning = FALSE, message = FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(ggbeeswarm)
library(ggsignif)
```

Load data set

```{r load_counts, message = FALSE, warning = FALSE}
data <- read_csv('../data/acoustics.csv')
```

Create subset for the comparison med-OFF vs DBS-OFF

And delete data of PD03, as he did not tolerate the DBS-OFF condition (n = 12)

```{r, message = FALSE, warning = FALSE}
data_red <-  filter(data, med_con %in% c('med-OFF', 'med-OFF/DBS-OFF'))

data_red <- subset(data_red, speaker != "PD03")
```

Descriptive stats for reporting values in Table 10.1

```{r, message = FALSE, warning = FALSE}

V1_stats <- data_red %>% 
  group_by(med_con) %>% 
  summarise(M = round(mean(V1.dur)),
            SD = round(sd(V1.dur)))
V1_stats 

V1_stats2 <- data_red %>% 
  group_by(med_con, focus_con) %>% 
  summarise(M = round(mean(V1.dur)),
            SD = round(sd(V1.dur)))
V1_stats2

```

# Statistical analysis

Load packages needed

```{r, message = FALSE, warning = FALSE}
library(lme4)
library(lmerTest)
library(sjPlot)
library(sjmisc)
library(merTools)
library(emmeans)

set.seed(42)
```

Create model with lmer.

```{r, message = FALSE, warning = FALSE}

## interaction 
mdl1 <- lmer(V1.dur ~ med_con * focus_con + (1+focus_con|speaker) + (1|vowel) + (1|cons), data_red, REML = FALSE)

mdl2 <- lmer(V1.dur ~ med_con + focus_con + (1+focus_con|speaker) + (1|vowel) + (1|cons), data_red, REML = FALSE)

anova(mdl1, mdl2) ## no interaction

## check focus

mdl2b <- lmer(V1.dur ~ med_con + 1 + (1+focus_con|speaker) + (1|vowel) + (1|cons), data_red, REML = FALSE)

anova(mdl2, mdl2b) ## effect of focus: X2(2) = 23.521, p = 7.808e-06

emmeans(mdl2, specs = pairwise ~ focus_con)

## check group

mdl2c <- lmer(V1.dur ~ 1 + focus_con + (1+focus_con|speaker) + (1|vowel) + (1|cons), data_red, REML = FALSE)

anova(mdl2, mdl2c) ## group effect: X2(1) = 29.042, p = 7.082e-08

emmeans(mdl2, specs = pairwise ~ med_con)

```