---
title: "Acoustic Analysis"
author: "Tabea Thies"
date: "`r Sys.Date()`"
output: html_document
---

# Analysis of levodopa effect on acoustic vowel duration in speakers with PD

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load necessary packages

```{r load_tidyverse, warning = FALSE, message = FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(ggbeeswarm)
library(ggsignif)
```

Load data set

```{r load_counts, message = FALSE, warning = FALSE}
data <- read_csv('../data/acoustics.csv')
```

Create subset for the comparison med-OFF vs med-ON

```{r, message = FALSE, warning = FALSE}
data_red <-  filter(data, med_con %in% c('med-OFF', 'med-ON'))
```

Descriptive stats for reporting values in Table 7.1 and Section 7.2.2

```{r, message = FALSE, warning = FALSE}

V1_stats <- data_red %>% 
  group_by(med_con) %>% 
  summarise(M = round(mean(V1.dur)),
            SD = round(sd(V1.dur)))
V1_stats 

V1_stats2 <- data_red %>% 
  group_by(med_con, focus_con) %>% 
  summarise(M = round(mean(V1.dur)),
            SD = round(sd(V1.dur)))
V1_stats2

V1_stats3 <- data_red %>% 
  group_by(speaker, med_con, focus_con) %>% 
  summarise(M = mean(V1.dur),
            SD = sd(V1.dur))
V1_stats3

V1_stats4 <- data_red %>% 
  group_by(speaker, med_con) %>% 
  summarise(M = mean(V1.dur),
            SD = sd(V1.dur))
V1_stats4

```

Plot means per group and focus condition (Figure 7.2)


```{r, message = FALSE, warning = FALSE, fig.height = 3, fig.width = 6,}

plot01 <- V1_stats3 %>% 
  ggplot(aes(x = med_con, y = M, group = speaker)) +
  geom_point(aes(col = med_con), shape = 19, alpha = 0.7, size = 6) +
  geom_line(col = 'darkgrey') +
  facet_grid(.~focus_con)+
  theme_classic() +
  theme(legend.position = 'none')+
  scale_color_manual(values = c('#BE7592', '#74BDA0')) +
  coord_cartesian(ylim = c(70, 230)) + 
  scale_y_continuous(breaks = seq(80, 220, 40)) +
  xlab(NULL) +
  scale_x_discrete(labels = c('med-OFF','med-ON'))+
  ylab("Vowel Duration (ms)")+
  theme(axis.title.y = element_text(face = 'bold', size = 22, margin = margin(r = 12)))+
  theme(strip.text.x = element_text(size=30, face="bold"),
        strip.background = element_blank())+
  theme(axis.text.x = element_text(size = 22),
        axis.text.y = element_text(size = 22)) +
  theme(axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank())

ggsave(plot01, filename = '../plots/V1_dur_PD_preop.png',
       width = 12, height = 5, dpi = 300)

```

# Statistical analysis

Load packages needed

```{r, message = FALSE, warning = FALSE}
library(lme4)
library(lmerTest)
library(sjPlot)
library(sjmisc)
library(merTools)
library(emmeans)

set.seed(42)
```

Create model with lmer.

```{r, message = FALSE, warning = FALSE}

## interaction 
mdl1 <- lmer(V1.dur ~ med_con * focus_con + (1+focus_con|speaker) + (1|vowel) + (1|cons), data_red, REML = FALSE)

mdl2 <- lmer(V1.dur ~ med_con + focus_con + (1+focus_con|speaker) + (1|vowel) + (1|cons), data_red, REML = FALSE)

anova(mdl1, mdl2) ## no interaction

## check focus

mdl2b <- lmer(V1.dur ~ med_con + 1 + (1+focus_con|speaker) + (1|vowel) + (1|cons), data_red, REML = FALSE)

anova(mdl2, mdl2b) ## effect of focus: X2(2) = 20.403, p = 3.712e-05

emmeans(mdl2, specs = pairwise ~ focus_con)

## check group

mdl2c <- lmer(V1.dur ~ 1 + focus_con + (1+focus_con|speaker) + (1|vowel) + (1|cons), data_red, REML = FALSE)

anova(mdl2, mdl2c) ## no group effect: X2(1) = 1.8629, p = 0.1723

```