---
title: "Acoustic Analysis"
author: "Tabea Thies"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

# Analysis of acoustic vowel duration comparing healthy controls and speakers with PD (med-OFF)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load necessary packages

```{r load_tidyverse, warning = FALSE, message = FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(ggbeeswarm)
library(ggsignif)
```

Load data set

```{r load_counts, message = FALSE, warning = FALSE}
data <- read_csv('../data/acoustics.csv')

```

Create subset for the comparison Controls vs PD (in med-OFF)

```{r, message = FALSE, warning = FALSE}
data_red <-  filter(data, med_con %in% c('Control', 'med-OFF'))
```

Plot means per group and focus condition (Figure 6.1)

```{r, message = FALSE, warning = FALSE}

group_names <- as_labeller(
     c(`Control` = "CON", `med-OFF` = "PD"))

DUR_plot <- data_red %>% 
  group_by(med_con, focus_con, speaker) %>% 
  summarise(M = round(mean(V1.dur)),
            SD = round(sd(V1.dur)))

plot01 <- DUR_plot %>%
  ggplot(aes(x=focus_con, y=M, fill=focus_con)) +
  geom_boxplot(width=0.4, color="black", alpha=0.1, outlier.alpha = 0.1) +
  stat_boxplot(geom = "errorbar", width = 0.1) + 
  geom_dotplot(binaxis='y', stackdir='center', dotsize=1)+
  theme_classic() +
  theme(legend.position = 'bottom')+
  theme(legend.title = element_blank(),
        legend.text = element_text(size = 28))+
  scale_fill_manual(values = c("#8da0cb", "#66c2a5", "#fc8d62")) +
  xlab(NULL) +
  facet_grid(.~med_con, labeller = group_names)+
  ylab("Vowel Duration (ms)")+
  coord_cartesian(ylim = c(70, 210)) + 
  scale_y_continuous(breaks = seq(80, 200, 40)) +
  theme(axis.title.y = element_text(face = 'bold', size = 30, margin = margin(r = 30)))+
  theme(strip.text.x = element_text(size=32, face="bold"),
        strip.background = element_blank())+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(size = 28)) +
  theme(axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank())

ggsave(plot01, filename = '../plots/V1dur_CON_PD.png',
       width = 12, height = 7, dpi = 300)
```

# Statistical analysis

Load packages needed

```{r, message = FALSE, warning = FALSE}
library(lme4)
library(lmerTest)
library(sjPlot)
library(sjmisc)
library(merTools)
library(emmeans)

set.seed(42)
```

Create model with lmer

```{r, message = FALSE, warning = FALSE}

## interaction 
mdl1 <- lmer(V1.dur ~ med_con * focus_con + (1+focus_con|speaker) + (1|vowel) + (1|cons), data_red, REML = FALSE)

mdl2 <- lmer(V1.dur ~ med_con + focus_con + (1+focus_con|speaker) + (1|vowel) + (1|cons), data_red, REML = FALSE)

anova(mdl1, mdl2) ## no interaction

## check focus

mdl2b <- lmer(V1.dur ~ med_con + 1 + (1+focus_con|speaker) + (1|vowel) + (1|cons), data_red, REML = FALSE)

anova(mdl2, mdl2b) ## effect of focus: X2(2) = 31.407, p = 1.514e-07

emmeans(mdl2, specs = pairwise ~ focus_con)

## check group

mdl2c <- lmer(V1.dur ~ 1 + focus_con + (1+focus_con|speaker) + (1|vowel) + (1|cons), data_red, REML = FALSE)

anova(mdl2, mdl2c) ## group effect: X2(1) = 5.1666, p = 0.02303

emmeans(mdl2, specs = pairwise ~ med_con)


```